### PR TITLE
Sublimelinter4

### LINKED ISSUE #5: SublimeLinter 4 will stop supporting inline settings
We're making big changes to SublimeLinter and version 4 will no longer support inline settings. Users should migrate to configuration features of their particular linter, in this case to ansible-lint config files. 

Additionally we now recommend against replication such configuration features in SL linter plugins. When you update this plugin you could consider removing any such settings to simplify and future-proof it.

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Update code to be compatible with changes required by SublimeLinter 4.

fixes #5

### CODE REVIEW

**Comment by nvtkaszpir** [comment]
Do not merge yet, it shows lint errors from different files in current view, see https://github.com/SublimeLinter/SublimeLinter/issues/1238

**Comment by KingJ** [comment]
What's the latest here? I've just tried cloning your `sublimelinter4-filter-view` branch and it appears to be working (or at least, in the console I get output from ansible-lint even if not in the Lint window, but that could be a side effect of how i'm running ansible-lint rather than any actual issues here!)

**Comment by GaboFDC** [comment]
Hello, i was checking this repo, and noticed that the owner @mliljedahl seems like beeing inactive for over a year.
idk if he still has time to maintain this, or if maybe this should be forked to a new maintainer?
What do u guys think?

**Comment by mliljedahl** [comment]
Hi, and sorry :) I will have a look tomorrow and get back to you.

**Comment by nvtkaszpir** [comment]
same here, time to look into this.

**Comment by GaboFDC** [comment]
Hi, just wanted to say thanks for the effort 💯
Really looking forward to update the package in sublime :)

**Comment by GaboFDC** [comment]
Hello, i don't wanna bother, but i'm just curious.
Now that the PR was merged, how is the process of update the plug-in in the package control?
Is it automatically? or something has to be made (like create a PR in SublimeLinter repo or any other repo) to get this shipped?

**Comment by GaboFDC** [comment]
After checking a bit more, i believe that the only thing missing is to make a release in the repo, tagging the new version.
@mliljedahl do you have some time to do it?

**Comment by mliljedahl** [comment]
Yes, that is correct, will try to do that asap. The readme also need an
update

Den mån 27 aug. 2018 18:39Gabriel <notifications@github.com> skrev:

**Pull request merged**
